# Generated by Django 4.1.2 on 2022-10-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_facebook_user_github_user_linkedin_user_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
